In [283]:
#Lets import all the librarikes required to build a model
import numpy as np
import pandas as pd
import tensorflow as tf
import re
import nltk

import pandas as pd
import numpy as np

from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
print('imported')

imported

In [250]:
#import the training dataset
train_comment_raw=pd.read_csv('../data/train/train.csv')

In [251]:
#declare the limit of data to be used
data_limiter=2000

In [252]:
train_df=pd.DataFrame(train_comment_raw)

In [255]:
#Lets check the stat of dataset how the data is distributed.
train_df.describe()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
count,9.585100e+04,95851.000000,95851.000000,95851.000000,95851.000000,95851.000000,95851.000000
mean,4.994359e+11,0.096368,0.010068,0.053301,0.003182,0.049713,0.008492
std,2.890136e+11,0.295097,0.099832,0.224635,0.056320,0.217352,0.091762
min,2.225664e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.473437e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.001297e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.501088e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.999882e+11,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [256]:
#initail data  chunk of data with raw data
train_df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,22256635,"Nonsense? kiss off, geek. what I said is true...",1,0,0,0,0,0
1,27450690,"""\n\n Please do not vandalize pages, as you di...",0,0,0,0,0,0
2,54037174,"""\n\n """"Points of interest"""" \n\nI removed the...",0,0,0,0,0,0
3,77493077,Asking some his nationality is a Racial offenc...,0,0,0,0,0,0
4,79357270,The reader here is not going by my say so for ...,0,0,0,0,0,0

In [257]:
train_df.head()

# train_df[train_df.apply(lambda x: x['toxic'] ==1, axis=1, reduce=True)]

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,22256635,"Nonsense? kiss off, geek. what I said is true...",1,0,0,0,0,0
1,27450690,"""\n\n Please do not vandalize pages, as you di...",0,0,0,0,0,0
2,54037174,"""\n\n """"Points of interest"""" \n\nI removed the...",0,0,0,0,0,0
3,77493077,Asking some his nationality is a Racial offenc...,0,0,0,0,0,0
4,79357270,The reader here is not going by my say so for ...,0,0,0,0,0,0

In [262]:
#create new feature count of  toxic
def count_toxic(row):
    count=0
    for i in range(2,8):
        if row[i]==1:
            count+=1
    return count
    
    
train_df['toxic_level']=train_df.apply(count_toxic,axis=1)

In [263]:
# sort the data based on count of toxic
sorted_comment_df=train_df.sort_values(by='toxic_level', ascending=False)
sorted_comment_df=sorted_comment_df.head(data_limiter)
sorted_comment_df.head()['comment_text']

12544    u motherfukkin bitch i want to rape you smelly...
19550    GO FUCK YOURSELF BITCH.  I HATE YOUR SOULD.  M...
65099    YOURE A FRREAKING JEW, AND PLEAZE COMMIT SUICIDE.
22131    Bitch \n\nYou are a little bitch. I fuckin spe...
9708     ANYONE WHO SUPPORTS THIS IS FUCKING SICK. MEN ...
Name: comment_text, dtype: object

In [275]:
#remove extra words
def remove_extra_text( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text=BeautifulSoup(review).get_text()
    #
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]

    #
    # 5. Return a list of words
    return(' '.join(words))

In [279]:
#actual cleaning 
def clean_text(row):
    return remove_extra_text(row['comment_text'])
sorted_comment_df['comment_text']=sorted_comment_df.apply(clean_text,axis=1)

h:\python35\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 184 of the file h:\python35\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "html5lib")

  markup_type=markup_type))

In [282]:
#sorted and clean data
sorted_comment_df.head(10)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,toxic_level
12544,129603955806,u motherfukkin bitch i want to rape you smelly...,1,1,1,1,1,1,6
19550,202833088469,go fuck yourself bitch i hate your sould mothe...,1,1,1,1,1,1,6
65099,678039220839,youre a frreaking jew and pleaze commit suicide,1,1,1,1,1,1,6
22131,228522837108,bitch you are a little bitch i fuckin spent ho...,1,1,1,1,1,1,6
9708,100240833617,anyone who supports this is fucking sick men a...,1,1,1,1,1,1,6
4847,50567420301,you re a stupid cunt fuck you dumb arse your m...,1,1,1,1,1,1,6
57708,601256246979,fuck all asyriac nation qamishli belong to arm...,1,1,1,1,1,1,6
90076,940615911114,jew get the fuck out of here you jewish son of...,1,1,1,1,1,1,6
20333,210792237054,faggots yo fucker it was fucking hayes you fag...,1,1,1,1,1,1,6
47339,493691492802,so fuck off and die rape fantasising sluts,1,1,1,1,1,1,6

In [284]:
#text to vector 
vectorizer = CountVectorizer(analyzer = "word")
converted_comment_to_vector=vectorizer.fit_transform(sorted_comment_df['comment_text'])

In [285]:
np.array(vectorizer.get_feature_names()).shape

(8491,)

In [287]:
converted_comment_to_vector.toarray().shape

(2000, 8491)

In [223]:
weight={
    'w1':tf.Variable(tf.random_normal([8491,10000])),
    'w1':tf.Variable(tf.random_normal([10000,10000])),
    'w3':tf.Variable(tf.random_normal([10000,8491]))
    
    
}

In [225]:
sample_submission=pd.read_csv('../data/sample_submission/sample_submission.csv')

In [227]:
sample_submission.head(100)

           id  toxic  severe_toxic  obscene  threat  insult  identity_hate
0     6044863    0.5           0.5      0.5     0.5     0.5            0.5
1     6102620    0.5           0.5      0.5     0.5     0.5            0.5
2    14563293    0.5           0.5      0.5     0.5     0.5            0.5
3    21086297    0.5           0.5      0.5     0.5     0.5            0.5
4    22982444    0.5           0.5      0.5     0.5     0.5            0.5
5    24388733    0.5           0.5      0.5     0.5     0.5            0.5
6    26195914    0.5           0.5      0.5     0.5     0.5            0.5
7    31769073    0.5           0.5      0.5     0.5     0.5            0.5
8    35289443    0.5           0.5      0.5     0.5     0.5            0.5
9    38393350    0.5           0.5      0.5     0.5     0.5            0.5
10   51720630    0.5           0.5      0.5     0.5     0.5            0.5
11   52808210    0.5           0.5      0.5     0.5     0.5            0.5
12   53780387    0.5           0.5      0.5     0.5     0.5            0.5
13   55969236    0.5           0.5      0.5     0.5     0.5            0.5
14   59321043    0.5           0.5      0.5     0.5     0.5            0.5
15   59993753    0.5           0.5      0.5     0.5     0.5            0.5
16   60087415    0.5           0.5      0.5     0.5     0.5            0.5
17   62246374    0.5           0.5      0.5     0.5     0.5            0.5
18   63082469    0.5           0.5      0.5     0.5     0.5            0.5
19   66675140    0.5           0.5      0.5     0.5     0.5            0.5
20   68336055    0.5           0.5      0.5     0.5     0.5            0.5
21   70790434    0.5           0.5      0.5     0.5     0.5            0.5
22   71559114    0.5           0.5      0.5     0.5     0.5            0.5
23   72407499    0.5           0.5      0.5     0.5     0.5            0.5
24   75557079    0.5           0.5      0.5     0.5     0.5            0.5
25   75694081    0.5           0.5      0.5     0.5     0.5            0.5
26   82999985    0.5           0.5      0.5     0.5     0.5            0.5
27   84135100    0.5           0.5      0.5     0.5     0.5            0.5
28   88993345    0.5           0.5      0.5     0.5     0.5            0.5
29   90125467    0.5           0.5      0.5     0.5     0.5            0.5
..        ...    ...           ...      ...     ...     ...            ...
70  248204624    0.5           0.5      0.5     0.5     0.5            0.5
71  251031836    0.5           0.5      0.5     0.5     0.5            0.5
72  263011428    0.5           0.5      0.5     0.5     0.5            0.5
73  263965152    0.5           0.5      0.5     0.5     0.5            0.5
74  272093244    0.5           0.5      0.5     0.5     0.5            0.5
75  273386057    0.5           0.5      0.5     0.5     0.5            0.5
76  277563362    0.5           0.5      0.5     0.5     0.5            0.5
77  277995993    0.5           0.5      0.5     0.5     0.5            0.5
78  282638939    0.5           0.5      0.5     0.5     0.5            0.5
79  299777429    0.5           0.5      0.5     0.5     0.5            0.5
80  304612610    0.5           0.5      0.5     0.5     0.5            0.5
81  310052309    0.5           0.5      0.5     0.5     0.5            0.5
82  311294998    0.5           0.5      0.5     0.5     0.5            0.5
83  311813300    0.5           0.5      0.5     0.5     0.5            0.5
84  312715824    0.5           0.5      0.5     0.5     0.5            0.5
85  313513079    0.5           0.5      0.5     0.5     0.5            0.5
86  327378720    0.5           0.5      0.5     0.5     0.5            0.5
87  327545745    0.5           0.5      0.5     0.5     0.5            0.5
88  330695588    0.5           0.5      0.5     0.5     0.5            0.5
89  330828508    0.5           0.5      0.5     0.5     0.5            0.5
90  333051738    0.5           0.5      0.5     0.5     0.5            0.5
91  347578051    0.5           0.5      0.5     0.5     0.5            0.5
92  352987131    0.5           0.5      0.5     0.5     0.5            0.5
93  355259307    0.5           0.5      0.5     0.5     0.5            0.5
94  356215248    0.5           0.5      0.5     0.5     0.5            0.5
95  360915651    0.5           0.5      0.5     0.5     0.5            0.5
96  363250160    0.5           0.5      0.5     0.5     0.5            0.5
97  363416869    0.5           0.5      0.5     0.5     0.5            0.5
98  363683089    0.5           0.5      0.5     0.5     0.5            0.5
99  364230321    0.5           0.5      0.5     0.5     0.5            0.5

[100 rows x 7 columns]

In [244]:
rowsums=sorted_comment_df.iloc[:,2:].sum(axis=1)
train['clean']=(rowsums==0)

12544    12
19550    12
65099    12
22131    12
9708     12
4847     12
57708    12
90076    12
20333    12
47339    12
32686    12
47057    12
72460    12
38634    12
7258     12
40211    12
36720    12
58447    12
42210    12
23621    12
76186    10
87401    10
6772     10
73658    10
87900    10
20992    10
51283    10
69699    10
22981    10
20590    10
         ..
81882     6
5497      6
46052     6
37968     6
90912     6
19384     6
64546     6
78470     6
61770     6
90899     6
54527     6
64584     6
34792     6
53276     6
53279     6
81944     6
64642     6
64640     6
78369     6
78789     6
61709     6
19458     6
64585     6
19457     6
81932     6
64594     6
61721     6
78411     6
3835      6
47384     6
Length: 2000, dtype: int64

In [248]:
sorted_comment_df.isnull().count()

id               2000
comment_text     2000
toxic            2000
severe_toxic     2000
obscene          2000
threat           2000
insult           2000
identity_hate    2000
toxic_level      2000
dtype: int64

In [206]:
converted_comment_to_vector.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [207]:
converted_comment_to_vector=np.array(converted_comment_to_vector.toarray())

In [208]:
converted_comment_to_vector[0][:1000]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [209]:
converted_comment_to_vector.shape

(2000, 8491)